import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yusuf
 */
public class NewJFrame extends javax.swing.JFrame {
    
    public NewJFrame() {
        initComponents();
        jPanel2.setVisible(false);
        labelReport.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        labelYear1 = new javax.swing.JLabel();
        textField_sems1 = new javax.swing.JTextField();
        textField_sems2 = new javax.swing.JTextField();
        gpaBtn = new javax.swing.JButton();
        labelCourse = new javax.swing.JLabel();
        labelYear2 = new javax.swing.JLabel();
        labelYear3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        textField_sems3 = new javax.swing.JTextField();
        textField_sems5 = new javax.swing.JTextField();
        textField_sems4 = new javax.swing.JTextField();
        textField_sems6 = new javax.swing.JTextField();
        reportBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        labelAverage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelSemester = new javax.swing.JLabel();
        labelMarks = new javax.swing.JLabel();
        labelPercentage = new javax.swing.JLabel();
        sems1 = new javax.swing.JLabel();
        sems2 = new javax.swing.JLabel();
        sems3 = new javax.swing.JLabel();
        sems4 = new javax.swing.JLabel();
        sems5 = new javax.swing.JLabel();
        sems6 = new javax.swing.JLabel();
        labelMark6 = new javax.swing.JLabel();
        labelMark1 = new javax.swing.JLabel();
        labelMark2 = new javax.swing.JLabel();
        labelMark3 = new javax.swing.JLabel();
        labelMark4 = new javax.swing.JLabel();
        labelMark5 = new javax.swing.JLabel();
        labelPerc1 = new javax.swing.JLabel();
        labelPerc2 = new javax.swing.JLabel();
        labelPerc3 = new javax.swing.JLabel();
        labelPerc4 = new javax.swing.JLabel();
        labelPerc5 = new javax.swing.JLabel();
        labelPerc6 = new javax.swing.JLabel();
        labelReport = new javax.swing.JLabel();
        radioBtn_mba = new javax.swing.JRadioButton();
        radioBtn_mca = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelTotalMarks = new javax.swing.JLabel();
        labelAvrgMarks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelYear1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelYear1.setText("Year 1");
        getContentPane().add(labelYear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        textField_sems1.setName(""); // NOI18N
        textField_sems1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField_sems1KeyPressed(evt);
            }
        });
        getContentPane().add(textField_sems1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 55, -1));
        textField_sems1.getAccessibleContext().setAccessibleName("");
        textField_sems1.getAccessibleContext().setAccessibleDescription("Alo");

        textField_sems2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField_sems2KeyPressed(evt);
            }
        });
        getContentPane().add(textField_sems2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 55, -1));

        gpaBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gpaBtn.setText("GPA");
        gpaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(gpaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        labelCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCourse.setText("Course");
        getContentPane().add(labelCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 54, -1));

        labelYear2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelYear2.setText("Year 2");
        getContentPane().add(labelYear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        labelYear3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelYear3.setText("Year 3");
        getContentPane().add(labelYear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 49, -1));

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotal.setText("Total");
        getContentPane().add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 49, -1));

        textField_sems3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField_sems3KeyPressed(evt);
            }
        });
        getContentPane().add(textField_sems3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 55, -1));

        textField_sems5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField_sems5KeyPressed(evt);
            }
        });
        getContentPane().add(textField_sems5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 55, -1));

        textField_sems4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField_sems4KeyPressed(evt);
            }
        });
        getContentPane().add(textField_sems4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 55, -1));

        textField_sems6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField_sems6KeyPressed(evt);
            }
        });
        getContentPane().add(textField_sems6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 55, -1));

        reportBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportBtn.setText("Report");
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });
        getContentPane().add(reportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        labelAverage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAverage.setText("Average");
        getContentPane().add(labelAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 65, -1));

        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSemester.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSemester.setText("Semester");
        jPanel2.add(labelSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 10, -1, -1));

        labelMarks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMarks.setText("Marks");
        jPanel2.add(labelMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        labelPercentage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPercentage.setText("Percentage");
        jPanel2.add(labelPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 10, -1, -1));

        sems1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sems1.setText("1");
        jPanel2.add(sems1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        sems2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sems2.setText("2");
        jPanel2.add(sems2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        sems3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sems3.setText("3");
        jPanel2.add(sems3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        sems4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sems4.setText("4");
        jPanel2.add(sems4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        sems5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sems5.setText("5");
        jPanel2.add(sems5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        sems6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sems6.setText("6");
        jPanel2.add(sems6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 10, -1));

        labelMark6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelMark6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 70, 20));

        labelMark1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMark1.setToolTipText("");
        jPanel2.add(labelMark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 70, 20));

        labelMark2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelMark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 20));

        labelMark3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelMark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 20));

        labelMark4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelMark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, 20));

        labelMark5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelMark5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 70, 20));

        labelPerc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelPerc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 70, 20));

        labelPerc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelPerc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 70, 20));

        labelPerc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelPerc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 70, 20));

        labelPerc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelPerc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 70, 20));

        labelPerc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelPerc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 70, 20));

        labelPerc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelPerc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 70, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 360, 220));

        labelReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelReport.setText("Report");
        getContentPane().add(labelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        buttonGroup2.add(radioBtn_mba);
        radioBtn_mba.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioBtn_mba.setText("MBA");
        radioBtn_mba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_mbaActionPerformed(evt);
            }
        });
        getContentPane().add(radioBtn_mba, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        buttonGroup2.add(radioBtn_mca);
        radioBtn_mca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioBtn_mca.setText("MCA");
        radioBtn_mca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_mcaActionPerformed(evt);
            }
        });
        getContentPane().add(radioBtn_mca, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 40, 560));

        labelTotalMarks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelTotalMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 100, 20));

        labelAvrgMarks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelAvrgMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 100, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtn_mbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_mbaActionPerformed
        labelYear3.setVisible(false);
        textField_sems5.setVisible(false);
        textField_sems6.setVisible(false);
        sems5.setVisible(false);
        sems6.setVisible(false);
        labelMark5.setVisible(false);
        labelMark6.setVisible(false);
        labelPerc5.setVisible(false);
        labelPerc6.setVisible(false);
        textField_sems1.setText("");
        textField_sems2.setText("");
        textField_sems3.setText("");
        textField_sems4.setText("");
        labelTotalMarks.setText("");
        labelAvrgMarks.setText("");
        labelReport.setVisible(false);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_radioBtn_mbaActionPerformed

    private void radioBtn_mcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_mcaActionPerformed
        labelYear3.setVisible(true);
        textField_sems5.setVisible(true);
        textField_sems6.setVisible(true);
        sems5.setVisible(true);
        sems6.setVisible(true);
        labelMark5.setVisible(true);
        labelMark6.setVisible(true);
        labelPerc5.setVisible(true);
        labelPerc6.setVisible(true);
        textField_sems1.setText("");
        textField_sems2.setText("");
        textField_sems3.setText("");
        textField_sems4.setText("");
        textField_sems5.setText("");
        textField_sems6.setText("");
        labelTotalMarks.setText("");
        labelAvrgMarks.setText("");
        labelReport.setVisible(false);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_radioBtn_mcaActionPerformed

    private void gpaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaBtnActionPerformed
        
        double sems1,sems2,sems3,sems4,sems5,sems6,res_mba,res_mca,avrg_mba,avrg_mca,gpa_mba,gpa_mca;
        
        if (radioBtn_mba.isSelected())
        {
            if (textField_sems1.getText().length() == 0 || textField_sems2.getText().length() == 0 || textField_sems3.getText().length() == 0 || textField_sems4.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Please enter all your marks!");
            }
            else if (Double.parseDouble(textField_sems1.getText()) > 600 || Double.parseDouble(textField_sems2.getText()) > 600 || Double.parseDouble(textField_sems3.getText()) > 600 || Double.parseDouble(textField_sems4.getText()) > 600)
            {
                JOptionPane.showMessageDialog(rootPane, "Error, Maximum mark is 600!");
            }
            else
            {
                sems1 = Double.parseDouble(textField_sems1.getText());
                sems2 = Double.parseDouble(textField_sems2.getText());
                sems3 = Double.parseDouble(textField_sems3.getText());
                sems4 = Double.parseDouble(textField_sems4.getText());
                res_mba = sems1+sems2+sems3+sems4;
                avrg_mba = res_mba/2400;
                gpa_mba = avrg_mba/10;
                
                //Total, Average, GPA (MBA)
                
                labelTotalMarks.setText(Double.toString(res_mba));
                labelAvrgMarks.setText(Double.toString((Math.round(avrg_mba)*100.0)/100.0)); //Math.round(num*100.0)/100.0 to get the nearest two digits
                JOptionPane.showMessageDialog(rootPane, "GPA = " + Math.round(gpa_mba*1000.0)/1000.0); //Math.round(num*1000.0)/1000.0 to get the nearest three digits
            }
        }
        else if (radioBtn_mca.isSelected())
        {
            if (textField_sems1.getText().length() == 0 || textField_sems2.getText().length() == 0 || textField_sems3.getText().length() == 0 || textField_sems4.getText().length() == 0 || textField_sems5.getText().length() == 0 || textField_sems6.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Please enter all your marks!");
            }
            else if (Double.parseDouble(textField_sems1.getText()) > 600 || Double.parseDouble(textField_sems2.getText()) > 600 || Double.parseDouble(textField_sems3.getText()) > 600 || Double.parseDouble(textField_sems4.getText()) > 600 || Double.parseDouble(textField_sems5.getText()) > 600 || Double.parseDouble(textField_sems6.getText()) > 600)
            {
                JOptionPane.showMessageDialog(rootPane, "Error, Maximum mark is 600!");
            }
            else
            {
                sems1 = Double.parseDouble(textField_sems1.getText());
                sems2 = Double.parseDouble(textField_sems2.getText());
                sems3 = Double.parseDouble(textField_sems3.getText());
                sems4 = Double.parseDouble(textField_sems4.getText());
                sems5 = Double.parseDouble(textField_sems5.getText());
                sems6 = Double.parseDouble(textField_sems6.getText());
                res_mca = sems1+sems2+sems3+sems4+sems5+sems6;
                avrg_mca = res_mca/3600;
                gpa_mca = avrg_mca/10;
                
                //Total, Average, GPA (MCA)
                
                labelTotalMarks.setText(Double.toString(res_mca));
                labelAvrgMarks.setText(Double.toString(Math.round(avrg_mca*100.0)/100.0)); //Math.round(num*100.0)/100.0 to get the nearest two digits
                JOptionPane.showMessageDialog(rootPane, "GPA = " + Math.round(gpa_mca*1000.0)/1000.0); //Math.round(num*1000.0)/1000.0 to get the nearest three digits
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Please select your course!");
        }
    }//GEN-LAST:event_gpaBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed

        int x = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to leave?", "Closing activity", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (x == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        
        double perc1,perc2,perc3,perc4,perc5,perc6,pr1,pr2,pr3,pr4,pr5,pr6;
        int n = 600;
        if (radioBtn_mba.isSelected())
        {
            if (textField_sems1.getText().length() == 0 || textField_sems2.getText().length() == 0 || textField_sems3.getText().length() == 0 || textField_sems4.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Please enter all your marks!");
            }
            else
            {
                labelReport.setVisible(true);
                jPanel2.setVisible(true);
                
                pr1 = Double.parseDouble(textField_sems1.getText());
                perc1 = Math.round(pr1/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
        
                pr2 = Double.parseDouble(textField_sems2.getText());
                perc2 = Math.round(pr2/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
        
                pr3 = Double.parseDouble(textField_sems3.getText());
                perc3 = Math.round(pr3/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
        
                pr4 = Double.parseDouble(textField_sems4.getText());
                perc4 = Math.round(pr4/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
                
                //Marks
                labelMark1.setText(textField_sems1.getText());
                labelMark2.setText(textField_sems2.getText());
                labelMark3.setText(textField_sems3.getText());
                labelMark4.setText(textField_sems4.getText());
                
                //Percentages
                labelPerc1.setText(Double.toString((perc1)) + " %");
                labelPerc2.setText(Double.toString((perc2)) + " %");
                labelPerc3.setText(Double.toString((perc3)) + " %");
                labelPerc4.setText(Double.toString((perc4)) + " %");
            }
        }
        else if (radioBtn_mca.isSelected())
        {
            if (textField_sems1.getText().length() == 0 || textField_sems2.getText().length() == 0 || textField_sems3.getText().length() == 0 || textField_sems4.getText().length() == 0 || textField_sems5.getText().length() == 0 || textField_sems6.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Please enter all your marks!");
            }
            else
            {
                labelReport.setVisible(true);
                jPanel2.setVisible(true);
                
                pr1 = Double.parseDouble(textField_sems1.getText());
                perc1 = Math.round(pr1/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
        
                pr2 = Double.parseDouble(textField_sems2.getText());
                perc2 = Math.round(pr2/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
        
                pr3 = Double.parseDouble(textField_sems3.getText());
                perc3 = Math.round(pr3/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
        
                pr4 = Double.parseDouble(textField_sems4.getText());
                perc4 = Math.round(pr4/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
                
                pr5 = Double.parseDouble(textField_sems5.getText());
                perc5 = Math.round(pr5/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
        
                pr6 = Double.parseDouble(textField_sems6.getText());
                perc6 = Math.round(pr6/n*100*10.0)/10.0; //Math.round(num*10.0)/10.0 to get the nearest digit
                
                //Marks
                labelMark1.setText(textField_sems1.getText());
                labelMark2.setText(textField_sems2.getText());
                labelMark3.setText(textField_sems3.getText());
                labelMark4.setText(textField_sems4.getText());
                labelMark5.setText(textField_sems5.getText());
                labelMark6.setText(textField_sems6.getText());
                
                //Percentages
                labelPerc1.setText(Double.toString((perc1)) + " %");
                labelPerc2.setText(Double.toString((perc2)) + " %");
                labelPerc3.setText(Double.toString((perc3)) + " %");
                labelPerc4.setText(Double.toString((perc4)) + " %");
                labelPerc5.setText(Double.toString((perc5)) + " %");
                labelPerc6.setText(Double.toString((perc6)) + " %");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Please select your course!");
        }
    }//GEN-LAST:event_reportBtnActionPerformed

    private void textField_sems1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_sems1KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter digits only!");
            textField_sems1.setText("");
        }
    }//GEN-LAST:event_textField_sems1KeyPressed

    private void textField_sems2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_sems2KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter digits only!");
            textField_sems2.setText("");
        }
    }//GEN-LAST:event_textField_sems2KeyPressed

    private void textField_sems3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_sems3KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter digits only!");
            textField_sems3.setText("");
        }
    }//GEN-LAST:event_textField_sems3KeyPressed

    private void textField_sems4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_sems4KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter digits only!");
            textField_sems4.setText("");
        }
    }//GEN-LAST:event_textField_sems4KeyPressed

    private void textField_sems5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_sems5KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter digits only!");
            textField_sems5.setText("");
        }
    }//GEN-LAST:event_textField_sems5KeyPressed

    private void textField_sems6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_sems6KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter digits only!");
            textField_sems6.setText("");
        }
    }//GEN-LAST:event_textField_sems6KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton exitBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton gpaBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAverage;
    private javax.swing.JLabel labelAvrgMarks;
    private javax.swing.JLabel labelCourse;
    private javax.swing.JLabel labelMark1;
    private javax.swing.JLabel labelMark2;
    private javax.swing.JLabel labelMark3;
    private javax.swing.JLabel labelMark4;
    private javax.swing.JLabel labelMark5;
    private javax.swing.JLabel labelMark6;
    private javax.swing.JLabel labelMarks;
    private javax.swing.JLabel labelPerc1;
    private javax.swing.JLabel labelPerc2;
    private javax.swing.JLabel labelPerc3;
    private javax.swing.JLabel labelPerc4;
    private javax.swing.JLabel labelPerc5;
    private javax.swing.JLabel labelPerc6;
    private javax.swing.JLabel labelPercentage;
    private javax.swing.JLabel labelReport;
    private javax.swing.JLabel labelSemester;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalMarks;
    private javax.swing.JLabel labelYear1;
    private javax.swing.JLabel labelYear2;
    private javax.swing.JLabel labelYear3;
    private javax.swing.JRadioButton radioBtn_mba;
    private javax.swing.JRadioButton radioBtn_mca;
    private javax.swing.JButton reportBtn;
    private javax.swing.JLabel sems1;
    private javax.swing.JLabel sems2;
    private javax.swing.JLabel sems3;
    private javax.swing.JLabel sems4;
    private javax.swing.JLabel sems5;
    private javax.swing.JLabel sems6;
    private javax.swing.JTextField textField_sems1;
    private javax.swing.JTextField textField_sems2;
    private javax.swing.JTextField textField_sems3;
    private javax.swing.JTextField textField_sems4;
    private javax.swing.JTextField textField_sems5;
    private javax.swing.JTextField textField_sems6;
    // End of variables declaration//GEN-END:variables
}
